
import { GoogleGenAI, Type } from "@google/genai";

const getApiKey = (): string | null => {
  const manualKey = localStorage.getItem('GEMINI_API_KEY');
  if (manualKey) return manualKey;
  const envKey = (process as any).env.API_KEY;
  if (envKey && envKey !== "undefined" && envKey !== "") return envKey;
  return null;
};

const getAI = () => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error("API Key가 설정되지 않았습니다. 상단 'API 키 설정' 버튼을 눌러주세요.");
  }
  return new GoogleGenAI({ apiKey });
};

export interface SchemaMapping {
  datasetName: string;
  tableName: string; // 새로 생성될 물리 테이블 이름
  sqlColumns: string; // CREATE TABLE에 들어갈 컬럼 정의 SQL
  mappings: { 
    source: string; 
    target: string; 
    type: 'string' | 'number'
  }[];
  xAxisLabel: string;
  yAxisLabel: string;
  unit: string;
}

export interface AIInsight {
  title: string;
  content: string;
  type: 'trend' | 'alert' | 'opportunity';
}

export interface AIRecommendation {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export interface DetailedAnalysis {
  reportTitle: string;
  summary: string;
  strategicSuggestions: string[];
  riskFactor: string;
}

/**
 * AI 기반 동적 테이블 스키마 생성 엔진
 */
export const identifyAndCreateDynamicSchema = async (sampleData: any[]): Promise<SchemaMapping> => {
  const ai = getAI();
  const sample = JSON.stringify(sampleData.slice(0, 10));
  
  const ANALYST_PERSONA = `
# Role: Senior Data Analyst & AI Engineer (Korean Native Context)

# Core Principles
1. **Cognitive Workflow**: Before answering, internally analyze the data domain, check for data integrity, and identify the business context.
2. **Language Rule**: 
   - **ALL user-facing text (titles, descriptions, summaries) MUST BE IN KOREAN.**
   - Technical identifiers (table_names, column_names, SQL types) must be in English (snake_case).
3. **Tone**: Professional, insightful, and strategic.
`;

/**
 * AI 기반 동적 테이블 스키마 생성 엔진
 */
export const identifyAndCreateDynamicSchema = async (sampleData: any[]): Promise<SchemaMapping> => {
  const ai = getAI();
  const sample = JSON.stringify(sampleData.slice(0, 10));
  
  // 변경된 프롬프트: 페르소나 적용 + 한글/영문 구분 명확화
  const prompt = `
    ${ANALYST_PERSONA}
    
    [Task]
    Analyze the provided Excel data sample and design a PostgreSQL schema.
    
    [Data Sample]
    ${sample}
    
    [Requirements]
    1. **Table Name**: Create a concise English snake_case name based on the data domain (e.g., 'monthly_sales_stats').
    2. **Column Names**: Map headers to semantic English snake_case names (e.g., '매출' -> 'revenue_amount').
    3. **SQL Types**: Assign the most appropriate PostgreSQL type (TEXT, NUMERIC, INTEGER, BOOLEAN, TIMESTAMP).
    4. **Dataset Name (datasetName)**: **MUST BE IN KOREAN.** Create a clear, descriptive title (e.g., '2024년 상반기 지역별 매출 현황').
    5. **Axis Labels**: **MUST BE IN KOREAN.** Suggest X/Y axis labels for a potential chart (e.g., '월별', '방문자 수').
    6. **Mandatory Fields**: You MUST include:
       - 'id' (bigint generated by default as identity primary key)
       - 'created_at' (timestamp with time zone default now())
    7. **Mappings**: Provide the source(Excel header) to target(English column) mapping.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview", // 최신 모델 권장
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            datasetName: { type: Type.STRING, description: "Korean title" },
            tableName: { type: Type.STRING },
            sqlColumns: { type: Type.STRING },
            mappings: { 
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  source: { type: Type.STRING },
                  target: { type: Type.STRING },
                  type: { type: Type.STRING, enum: ['string', 'number'] }
                },
                required: ["source", "target", "type"]
              }
            },
            xAxisLabel: { type: Type.STRING, description: "Korean label" },
            yAxisLabel: { type: Type.STRING, description: "Korean label" },
            unit: { type: Type.STRING, description: "Unit string (e.g., '원', '명')" }
          },
          required: ["datasetName", "tableName", "sqlColumns", "mappings", "xAxisLabel", "yAxisLabel", "unit"]
        }
      }
    });
    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    throw new Error(`동적 스키마 설계 실패: ${error.message}`);
  }
};

export const analyzeUploadedData = async (data: any[], schema: SchemaMapping) => {
  const ai = getAI();
  const dataSummary = data.slice(0, 30).map(d => JSON.stringify(d)).join("\n");
  
  // 변경된 프롬프트: 인사이트의 깊이 강화 + 한국어 출력 강제
  const prompt = `
    ${ANALYST_PERSONA}

    [Task]
    As a Senior Analyst, provide actionable insights and strategic recommendations in **Korean**.

    [Context]
    - Table Name: ${schema.tableName}
    - Dataset Title: ${schema.datasetName}
    - Data Summary: 
    ${dataSummary}

    [Analysis Instructions]
    1. **Insights**: Identify 3 key findings (Trend, Alert, Opportunity).
       - *Trend*: Significant patterns over time or categories.
       - *Alert*: Risks, anomalies, or negative outliers.
       - *Opportunity*: Areas for potential growth or improvement.
    2. **Recommendations**: Propose 3 concrete scenarios to address the insights.
    3. **Language**: **ALL titles, contents, and descriptions MUST be in natural, professional KOREAN.**
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            insights: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING, description: "In Korean" },
                  content: { type: Type.STRING, description: "In Korean" },
                  type: { type: Type.STRING, enum: ['trend', 'alert', 'opportunity'] }
                },
                required: ["title", "content", "type"]
              }
            },
            recommendations: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  title: { type: Type.STRING, description: "In Korean" },
                  description: { type: Type.STRING, description: "In Korean" },
                  icon: { type: Type.STRING }
                },
                required: ["id", "title", "description", "icon"]
              }
            }
          },
          required: ["insights", "recommendations"]
        }
      }
    });

    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    return null;
  }
};

export const getDeepDiveAnalysis = async (data: any[], recTitle: string, schema: SchemaMapping): Promise<DetailedAnalysis | null> => {
  const ai = getAI();
  const dataSummary = data.slice(0, 20).map(d => JSON.stringify(d)).join("\n");

  // 변경된 프롬프트: 보고서 형식 갖춤 + 한국어 비즈니스 톤
  const prompt = `
    ${ANALYST_PERSONA}

    [Task]
    Draft a professional Strategic Report in **Korean**.

    [Topic]
    "${recTitle}"

    [Data Context]
    - Dataset: ${schema.datasetName}
    - Evidence: ${dataSummary}

    [Structure Requirements]
    1. **Report Title**: A catchy and professional title in Korean.
    2. **Executive Summary**: A concise overview of the situation (Korean).
    3. **Strategic Suggestions**: A list of concrete, numbered action steps (Korean).
    4. **Risk Factor**: Potential risks or side effects to consider (Korean).
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            reportTitle: { type: Type.STRING },
            summary: { type: Type.STRING },
            strategicSuggestions: { type: Type.ARRAY, items: { type: Type.STRING } },
            riskFactor: { type: Type.STRING }
          },
          required: ["reportTitle", "summary", "strategicSuggestions", "riskFactor"]
        }
      }
    });
    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    return null;
  }
};