
import { GoogleGenAI, Type } from "@google/genai";

const getApiKey = (): string | null => {
  const manualKey = localStorage.getItem('GEMINI_API_KEY');
  if (manualKey) return manualKey;
  const envKey = (process as any).env.API_KEY;
  if (envKey && envKey !== "undefined" && envKey !== "") return envKey;
  return null;
};

const getAI = () => {
  const apiKey = getApiKey();
  if (!apiKey) {
    throw new Error("API Key가 설정되지 않았습니다. 상단 'API 키 설정' 버튼을 눌러주세요.");
  }
  return new GoogleGenAI({ apiKey });
};

export interface SchemaMapping {
  datasetName: string;
  tableName: string; // 새로 생성될 물리 테이블 이름
  sqlColumns: string; // CREATE TABLE에 들어갈 컬럼 정의 SQL
  mappings: { 
    source: string; 
    target: string; 
    type: 'string' | 'number'
  }[];
  xAxisLabel: string;
  yAxisLabel: string;
  unit: string;
}

export interface AIInsight {
  title: string;
  content: string;
  type: 'trend' | 'alert' | 'opportunity';
}

export interface AIRecommendation {
  id: string;
  title: string;
  description: string;
  icon: string;
}

export interface DetailedAnalysis {
  reportTitle: string;
  summary: string;
  strategicSuggestions: string[];
  riskFactor: string;
}

/**
 * AI 기반 동적 테이블 스키마 생성 엔진
 */
export const identifyAndCreateDynamicSchema = async (sampleData: any[]): Promise<SchemaMapping> => {
  const ai = getAI();
  const sample = JSON.stringify(sampleData.slice(0, 10));
  
  const prompt = `
    당신은 10년차 시니어 데이터 엔지니어입니다. 
    다음 엑셀 데이터를 분석하여 새로운 PostgreSQL 테이블을 생성하기 위한 스키마를 설계하세요.
    
    데이터 샘플: ${sample}
    
    [요구사항]
    1. 이 데이터셋을 가장 잘 나타내는 영문 테이블 이름을 정하세요 (예: regional_growth_2024). 공백없이 소문자와 언더바만 사용하세요.
    2. 모든 데이터 필드를 분석하여 최적의 컬럼명(영문 소문자/언더바)과 PostgreSQL 데이터 타입(TEXT, NUMERIC, INTEGER 등)을 정하세요.
    3. 'sqlColumns' 필드에 "column_name TYPE, column_name TYPE" 형식의 SQL 정의 문구를 작성하세요.
    4. 반드시 'id' 컬럼(bigint generated by default as identity primary key)과 'created_at' 컬럼(timestamp with time zone default now())을 포함시키세요.
    5. mappings 배열에는 (엑셀헤더명 -> 생성된 영문컬럼명) 매핑 정보를 담으세요.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            datasetName: { type: Type.STRING },
            tableName: { type: Type.STRING },
            sqlColumns: { type: Type.STRING },
            mappings: { 
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  source: { type: Type.STRING },
                  target: { type: Type.STRING },
                  type: { type: Type.STRING, enum: ['string', 'number'] }
                },
                required: ["source", "target", "type"]
              }
            },
            xAxisLabel: { type: Type.STRING },
            yAxisLabel: { type: Type.STRING },
            unit: { type: Type.STRING }
          },
          required: ["datasetName", "tableName", "sqlColumns", "mappings", "xAxisLabel", "yAxisLabel", "unit"]
        }
      }
    });
    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    throw new Error(`동적 스키마 설계 실패: ${error.message}`);
  }
};

export const analyzeUploadedData = async (data: any[], schema: SchemaMapping) => {
  const ai = getAI();
  const dataSummary = data.slice(0, 20).map(d => JSON.stringify(d)).join("\n");
  
  const prompt = `
    새로 생성된 테이블: ${schema.tableName}
    데이터셋 제목: ${schema.datasetName}
    데이터 요약: ${dataSummary}
    시니어 분석가로서 이 데이터에서 발견할 수 있는 3가지 핵심 인사이트와 3가지 심층 대응 시나리오를 제안하세요.
  `;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            insights: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  title: { type: Type.STRING },
                  content: { type: Type.STRING },
                  type: { type: Type.STRING, enum: ['trend', 'alert', 'opportunity'] }
                },
                required: ["title", "content", "type"]
              }
            },
            recommendations: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  id: { type: Type.STRING },
                  title: { type: Type.STRING },
                  description: { type: Type.STRING },
                  icon: { type: Type.STRING }
                },
                required: ["id", "title", "description", "icon"]
              }
            }
          },
          required: ["insights", "recommendations"]
        }
      }
    });

    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    return null;
  }
};

export const getDeepDiveAnalysis = async (data: any[], recTitle: string, schema: SchemaMapping): Promise<DetailedAnalysis | null> => {
  const ai = getAI();
  const dataSummary = data.slice(0, 15).map(d => JSON.stringify(d)).join("\n");

  const prompt = `분석 주제: "${recTitle}"\n데이터셋: ${schema.datasetName}\n샘플: ${dataSummary}\n전문적인 전략 리포트를 작성하세요.`;

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            reportTitle: { type: Type.STRING },
            summary: { type: Type.STRING },
            strategicSuggestions: { type: Type.ARRAY, items: { type: Type.STRING } },
            riskFactor: { type: Type.STRING }
          },
          required: ["reportTitle", "summary", "strategicSuggestions", "riskFactor"]
        }
      }
    });
    return JSON.parse(response.text || "{}");
  } catch (error: any) {
    return null;
  }
};
